# Generated by Django 4.1 on 2022-11-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempat_kuliner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempat_kuliner_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tempat_kuliner', models.TextField()),
                ('rating_tempat_kuliner', models.IntegerField()),
                ('lokasi_tempat_kuliner', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='item',
        ),
    ]
