# Generated by Django 4.1 on 2022-11-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempat_kuliner', '0002_tempat_kuliner_item_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempat_kuliner_item',
            name='rating_tempat_kuliner',
            field=models.CharField(max_length=10),
        ),
    ]
