# Generated by Django 4.1 on 2022-11-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='wisata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('provinsi', models.CharField(max_length=30)),
                ('alamat', models.CharField(max_length=200)),
                ('deskripsi', models.CharField(max_length=200)),
            ],
        ),
    ]
