# Generated by Django 4.1 on 2022-10-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuisioner_data_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuisioner',
            name='vaksin',
            field=models.CharField(max_length=10),
        ),
    ]
