# Generated by Django 4.1 on 2022-12-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuisioner_data_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuisioner',
            name='gender',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kuisioner',
            name='negara',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kuisioner',
            name='prov',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kuisioner',
            name='tujuan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kuisioner',
            name='vaksin',
            field=models.TextField(),
        ),
    ]
