# Generated by Django 4.1 on 2022-11-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuisioner_data_user', '0002_alter_kuisioner_vaksin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuisioner',
            name='nama',
            field=models.TextField(),
        ),
    ]
