# Generated by Django 4.1 on 2022-11-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuisioner_data_user', '0003_alter_kuisioner_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuisioner',
            name='kontak',
            field=models.IntegerField(),
        ),
    ]
