# Generated by Django 4.1 on 2022-11-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_remove_task_user'),
        ('activity', '0002_task_user'),
    ]

    operations = [
    ]
